### ISSUE TITLE
missing step /  can't successfully script/generate_tokens locally

### ISSUE THREAD

**Issue by johndpope** [izetex/contracts#1]
I acknowledge your efforts from code to documentation. very polished. 
I dived through half a dozen repos and even this repo outshines the zeppelin erc721 code quality in my opinion. I like the cheat sheet style of your readme. 
The scripts have also been super useful / invaluable. 
so much of this glue operations needed is not apparent in other repos and so time consuming. 

So I'm using ganache locally (similar to cli)
![screen shot 2018-05-15 at 13 31 30](https://user-images.githubusercontent.com/289994/40073558-269f653e-5845-11e8-84e6-4bc50c60ed8c.png)

I can successfully run all migrations. 
**truffle migrate --network ganache --reset**
```shell
Using network 'ganache'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x826735a62e7e44e647e593a7d7c823bc128235a940275621e34232dafa07b23b
  Migrations: 0x65ef0abf534c759101131a95bf169e8a2ba0e544
Saving successful migration to network...
  ... 0x64d40da98bbb2e4cdbcd85a7301809b9ce91a95e333c3df2bc81d37061fb7afd
Saving artifacts...
Running migration: 1511680476_izx_token.js
  Replacing IZXToken...
  ... 0x821835f412cc76d4c20e0dbe5ef6c11f0689c328765c1cd561d0593a4d91bd05
  IZXToken: 0x6303cf7486f13be7af909d32946c3aef1b421d60
Saving successful migration to network...
  ... 0x7611d4dcf97f6820c50457b84db5bc4ccb65473fd5d9a71ee03110bbfe615d2f
Saving artifacts...
Running migration: 1511766384_mutlisig.js
  Replacing Wallet...
  ... 0x9b82487866e0ff28ece4c91993e7a02c7917e42311ec9d2a8b5d267eeacdfe46
  Wallet: 0x61e9a713a48dcd769eb254b4c05a5358804ad3c5
Saving successful migration to network...
  ... 0xd240b6efa1a369e5ef5aa655cbb6c78b43d5f5b18d8addf74adb6959efa57e44
Saving artifacts...
Running migration: 1511767626_token_sale.js
  Running step...
  Replacing TokenSale...
  ... 0x14e2af4ca39091d235acdd6d571608ed3749448ecd2894830793990d2e981f4d
  TokenSale: 0xf2dd9b0b9bfc923fdac003cd8d3cf1858b801835
Saving successful migration to network...
  ... 0xfcf09ba926a24fc248e1adcaec44d1d2d286a82cbbe644ae30821ad46bcdd1b9
  ... 0x7708f9849e31cbce0e9a4ccbf53c51f806a219236849d6ad7526c302be4ab7db
Saving artifacts...
Running migration: 1514546678_drive_token.js
  Replacing DriveToken...
  ... 0x17731ffc8f42e2379e23cdb21a882c69bce9269692bcc85281e26df0648a1d6e
  DriveToken: 0x50fedc8609a716b1816d9afdf22b7194996fcdd3
Deployed DriveToken 0x50fedc8609a716b1816d9afdf22b7194996fcdd3
Saving successful migration to network...
  ... 0xba89d1d2af83d5040d5aa751ab2fe5db6d047fdfbfa5295529af11fceb04f262
Saving artifacts...
Running migration: 1521767620_token_driver.js
  Running step...
  Replacing TokenDriver...
  ... 0x6a59a62a79b6610453a76823e7fd4489fe46fb4e93bd91780f345c48b785760b
  TokenDriver: 0x6166d032f00267393d41d9d2ba088f3ca7be29bb
Token Driver 0x6166d032f00267393d41d9d2ba088f3ca7be29bb for IZX token: 0x6303cf7486f13be7af909d32946c3aef1b421d60 with controller: 0xf2dd9b0b9bfc923fdac003cd8d3cf1858b801835
Saving successful migration to network...
  ... 0xc5db56785ebee0c1a1d8d4e3b764a9fb9a8ce4f1335608467ceceb4029d1d45c
Saving artifacts...

```

![screen shot 2018-05-15 at 13 42 45](https://user-images.githubusercontent.com/289994/40073798-e3ca32ec-5845-11e8-89b1-142d816dab89.png)

**truffle.js config** 

```javascript

var HDWalletProvider = require("truffle-hdwallet-provider");
var mnemonic = "pave laundry same kingdom accuse stairs shop punch update wing year family";

module.exports = {
  networks: {
    ganache: {
      provider: function() {
        return new HDWalletProvider(mnemonic, "http://localhost:7545", 0)
      },
      port: 7545,
      network_id: 5777,      
      gas: 4600000
    }
  }
};

```
 I can successfully run a bunch of the test scripts.From each step - I can infer more data for updating config.js - might be an idea to have a script to spit out these settings - as I'm running reset with truffle and these all gets blown away. 

**script/config.js**
```javascript

module.exports = {
    ganache: {
        url: 'http://localhost:7545',
        creator: '0x019B38b68af82519DdbF1588276215e26C420a02', // my eth wallet address
        token: '0x98aa8abfaa76a453517c31d858462021ea870e02', // 
        game: '0xfb2fb88292b86f25ba70876a8392fa6fb64f45b7',
        drive_token: '0x3678ca9d737b543779e8acdf198dff14fd4863a7',
        token_driver: '0xf1bd0cc510219d46c37435efa091321dbf40ff3b',
        vault: '0x7D3005080787B4A8e40EBB7E68e52f6A03B0D7c0',//<-what step to generate this contract address?
        min_voting_duration: 3600,
        max_voting_duration: 8640000
    }
}

```

node script/deploy_izx_token - deploys IZX token

![screen shot 2018-05-15 at 13 44 53](https://user-images.githubusercontent.com/289994/40073911-2de623a4-5846-11e8-851a-12dfb29b6d68.png)

node script/generate_tokens - generate tokens and assign to token creator
**FAILS.**

![screen shot 2018-05-15 at 13 45 29](https://user-images.githubusercontent.com/289994/40073968-563656f8-5846-11e8-9deb-199be25887eb.png)

node script/deploy_drive_token - deploys DRIVE ERC721 token

**succeeds.**

node script/deploy_token_driver - deploys IZX Token driver
**succeeds.**

node script/change_controller - changes the controller for the token. If token alredy has a crowdsale defined as a controller, it uses the method in crowdsale contract. Otherwise, it calls the token method directly

node script/create_auction - create auction for ERC721 token

node script/create_campaign - create campaign for ERC721 token

I read about the vault - but not sure where to either generate it or spit out and existing contract address to update config.js settings. Is it not needed with localhost / ganache?

**Comment by johndpope** [comment]
if we share the same test nemonic it might help to align documentations.

**Comment by johndpope** [comment]
in generate_token script 
it says 
_only at ropsten we generate tokens manually_
I can assume perhaps that it's not necessary locally???

but my tests fail.


truffle test --network ganache
![screen shot 2018-05-15 at 14 33 48](https://user-images.githubusercontent.com/289994/40076494-011c6b7e-584d-11e8-862e-356ec2c85d55.png)

**Comment by johndpope** [comment]
tried adding        gas: 4600000 into ganache environment but still no joy

![screen shot 2018-05-15 at 14 37 34](https://user-images.githubusercontent.com/289994/40076658-8a69f928-584d-11e8-82c3-c1d6f57f7a28.png)

**Comment by johndpope** [comment]
so I can see some discrepancies in the script/contracts folder to the build/contracts folder.

one is wrapped with 
module.exports =
     {
    }


![screen shot 2018-05-15 at 15 27 46](https://user-images.githubusercontent.com/289994/40079071-9ccd883a-5854-11e8-8999-edeb9083e642.png)

is there a step to generate these contracts inside the script folder? 
I'm thinking this would break stuff.

**Comment by astudnev** [comment]
Hello, John! Thank you for the attention to our project. Actually the scripts are using the configuration of already deployed contracts, in script/config.js

When you run script in Ropsten you should deploy contracts as owner, and then modify this file

**Comment by astudnev** [comment]
As for tests  - try make a clean ganache run and start test. Will this error persist?
